"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-05 20:15:51.828112
"""

from datetime import UTC, datetime

import sqlalchemy as sa
from alembic import op

import sebastian.db

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("name_key", sa.String(length=80), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("requires_text", sa.Boolean(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("created_at", sebastian.db.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name_key"),
    )
    op.create_table(
        "series",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("rrule", sa.String(length=500), nullable=False),
        sa.Column("dtstart", sa.Date(), nullable=False),
        sa.Column("tz", sa.String(length=64), nullable=False),
        sa.Column("due_time", sa.String(length=5), nullable=False),
        sa.Column("nag_interval_min", sa.Integer(), nullable=True),
        sa.Column("quiet_hours", sa.String(length=11), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("generated_through", sebastian.db.UTCDateTime(), nullable=True),
        sa.Column("created_at", sebastian.db.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "setting",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "entry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("created_at", sebastian.db.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("entry", schema=None) as batch_op:
        batch_op.create_index("ix_entry_cat_created", ["category_id", "created_at"], unique=False)

    op.create_table(
        "task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("series_id", sa.Integer(), nullable=True),
        sa.Column("due_at", sebastian.db.UTCDateTime(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("done_at", sebastian.db.UTCDateTime(), nullable=True),
        sa.Column("snooze_until", sebastian.db.UTCDateTime(), nullable=True),
        sa.Column("nag_interval_min", sa.Integer(), nullable=True),
        sa.Column("quiet_hours", sa.String(length=11), nullable=True),
        sa.Column("nag_count", sa.Integer(), nullable=False),
        sa.Column("last_notified_at", sebastian.db.UTCDateTime(), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=False),
        sa.Column("created_at", sebastian.db.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["series_id"],
            ["series.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("series_id", "due_at", name="uq_task_series_due"),
    )
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.create_index("ix_task_status_due", ["status", "due_at"], unique=False)

    # ### end Alembic commands ###

    # Seed the built-in category used for plain notes.
    category = sa.table(
        "category",
        sa.column("name", sa.String),
        sa.column("name_key", sa.String),
        sa.column("description", sa.Text),
        sa.column("requires_text", sa.Boolean),
        sa.column("archived", sa.Boolean),
        sa.column("created_at", sa.DateTime),
    )
    op.bulk_insert(
        category,
        [
            {
                "name": "Note",
                "name_key": "note",
                "description": "Free-form note. Use for anything the user asks to be "
                "written down that is not a counted occurrence of another category.",
                "requires_text": True,
                "archived": False,
                "created_at": datetime.now(UTC).replace(tzinfo=None),
            }
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.drop_index("ix_task_status_due")

    op.drop_table("task")
    with op.batch_alter_table("entry", schema=None) as batch_op:
        batch_op.drop_index("ix_entry_cat_created")

    op.drop_table("entry")
    op.drop_table("setting")
    op.drop_table("series")
    op.drop_table("category")
    # ### end Alembic commands ###
